version: "3"
services:
  client:
    build: ./client
    container_name: react-ui
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
     - server
    networks:
     - mern-network
  server:
    build: ./server
    container_name: node-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
     - mern-network
  mongodb:
    image: "mongo"
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /kasutaja/Desktop/cloud computing/mongo-backup:/data/db
    networks:
     - mern-network
    
networks:
  mern-network:
    driver: bridge