apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: final-todo-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/todolist
---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  selector:
    app: node-api
  ports:
    - port: 8000
  type: NodePort